stages:
  - test
  - release

variables:
  GOPATH: ${CI_PROJECT_DIR}/.go

test:
  stage: test
  image: golang:1.24
  cache:
    key: go-modules
    paths:
      - .go/pkg/mod/
  script:
    - go fmt ./... && git diff --exit-code
    - go vet ./...
    - go test -race ./...

release:
  stage: release
  image: goreleaser/goreleaser:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean
